
name: login

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "mai" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Step 1 Check version Newman and Node
        run:
              newman --version
              node --version

      - name: Step 2 install Newman-Reporter-Htmlextra
        run: sudo npm install -g newman-reporter-htmalextra

      - name: Step 3 Execute collection
        run: newman run ./2_login.json -g ./global.json -e ./Postman.json --delay-request 1 --reports cli, -r htmlextra --reporter-htmlextra-export ./results/Report.html

      - name: Step 4 Archive production artifacts
        uses: actions/upload-artifact@v3
        with:

              name: report
              path: ./results/Report.html
              
        

        
